apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rick-morty.fullname" . }}
  labels:
    {{- include "rick-morty.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rick-morty.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rick-morty.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: rick-morty
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
