apiVersion: v1
kind: Service
metadata:
  name: {{ include "rick-morty.fullname" . }}
  labels:
    {{- include "rick-morty.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "rick-morty.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
