replicaCount: 1

image:
  repository: rick-morty-service
  tag: "2.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 8000

ingress:
  enabled: true
  hosts:
    - host: rick-morty.local
      paths:
        - path: /
          pathType: Prefix
